[[set]]
  category = 'tests'
  testSet = 'bngl'
  testerClass = 'TesterBnglPymcell4'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'bngl'
  testerClass = 'TesterBnglPymcell4'
  args = ['mcell4']  