# data model to pymcell4
[[set]]
  category = 'tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_chkpt'
  args = ['mcell4', 'checkpoints']
  
[[set]]
  category = 'tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl_chkpt'
  args = ['mcell4', 'convert_w_bngl', 'checkpoints']


[[set]]
  category = 'tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_chkpt'
  args = ['mcell4', 'checkpoints']
  
[[set]]
  category = 'tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl_chkpt'
  args = ['mcell4', 'convert_w_bngl', 'checkpoints']
  
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_chkpt'  
  args = ['mcell4', 'checkpoints']

[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl_chkpt'
  args = ['mcell4', 'convert_w_bngl', 'checkpoints']
  
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_chkpt'  
  args = ['mcell4', 'checkpoints']  
    
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl_chkpt'
  args = ['mcell4', 'convert_w_bngl', 'checkpoints']
    