[[set]]
  category = 'tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModel'
 
 [[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModel'
  