# data model to pymcell4
[[set]]
  category = 'tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl'
  args = ['mcell4', 'convert_w_bngl']


[[set]]
  category = 'tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl'
  args = ['mcell4', 'convert_w_bngl']
  
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  args = ['mcell4']

[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl'  
  args = ['mcell4', 'convert_w_bngl']
  
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  args = ['mcell4']  
    
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModelPymcell4'
  testDirSuffix = '_w_bngl'  
  args = ['mcell4', 'convert_w_bngl']
    