[[set]]
  category = 'utils_tests'
  testSet = 'bng_analyzer'
  testerClass = 'TesterExternal'
  args = [
    '$MCELL_TESTS_DIR/tests/utils_tests/bng_analyzer/test.sh', 
    '$MCELL_BUILD_DIR/utils/bng_analyzer/bng_analyzer', 
    '$MCELL_TESTS_DIR/tests/utils_tests/bng_analyzer/', 
    '$MCELL_TESTS_DIR/work/bng_analyzer'
  ]
    
[[set]]
  category = 'utils_tests'
  testSet = 'bng_analyzer_py'
  testerClass = 'TesterExternal'
  args = [
    'export MCELL_PATH=$MCELL_BUILD_DIR;',
    '$MCELL_TESTS_DIR/tests/utils_tests/bng_analyzer_py/test.sh', 
    '$MCELL_BUILD_DIR/utils/bng_analysis_example.py', 
    '$MCELL_TESTS_DIR/tests/utils_tests/bng_analyzer_py/', 
    '$MCELL_TESTS_DIR/work/bng_analyzer_py'
  ]
    
        
[[set]]
  category = 'external'
  testSet = 'bng_test'
  testerClass = 'TesterExternal'
  args = ['python3', '$MCELL_TESTS_DIR/../mcell/libs/bng/test/test.py', '$MCELL_BUILD_DIR']

[[set]]
  category = 'utils_tests'
  testSet = 'mcell4_runner/0000_seeds_w_fail'
  testerClass = 'TesterExternal'
  args = [
    '$MCELL_TESTS_DIR/tests/utils_tests/mcell4_runner/0000_seeds_w_fail/test.sh',
    '$MCELL_BUILD_DIR', '$MCELL_TESTS_DIR'
  ] 
  
[[set]]
  category = 'utils_tests'
  testSet = 'mcell4_runner/0001_args_file'
  testerClass = 'TesterExternal'
  args = [
    'export MCELL_PATH=$MCELL_BUILD_DIR;',
    'python3', 
    '$MCELL_BUILD_DIR/utils/mcell4_runner.py', 
    '$MCELL_TESTS_DIR/tests/utils_tests/mcell4_runner/0001_args_file/test.py', 
    '-a', '$MCELL_TESTS_DIR/tests/utils_tests/mcell4_runner/0001_args_file/test_args.txt'
  ] 
     
[[set]]
  category = 'utils_tests'
  testSet = 'mcell_pyi'
  testerClass = 'TesterExternal'
  args = [
    'python3', 
    '$MCELL_BUILD_DIR/utils/mcell.pyi'
  ]      
  