# TODO: add support for includes and reorganize

# tester_nutmeg_pymcell4.py
[[set]]
  category = 'tests'
  testSet = 'pymcell4_nutmeg'
  testerClass = 'TesterNutmegPymcell4'
  
  
# mcell4.toml
# MDL and nutmeg
[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterMdl'
  args = ['mcell4']

[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterMdl'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'nutmeg4_positive'
  testerClass = 'TesterNutmeg'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModel'
  args = ['mcell4']
  
# data_model_convert4.toml
# MDL to data model and back to MDL 
[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterDataModelConverter'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterDataModelConverter'
  args = ['mcell4']
  
# mdl_data_model_pymcell4.toml
# MDL to data model and then to pymcell4
[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  args = ['mcell4']
  
# data_model_pymcell4.toml
# data model to pymcell4
[[set]]
  category = 'tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'data_model'
  testerClass = 'TesterDataModelPymcell4'
  args = ['mcell4']
  
# part of pymcell4.toml  
[[set]]
  category = 'tests'
  testSet = 'pymcell4'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'pymcell4_positive'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']  

# bngl_to_pymcell4.toml
[[set]]
  category = 'tests'
  testSet = 'bngl'
  testerClass = 'TesterBnglPymcell4'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/models/hebrew_univ_jerusalem'
  testSet = 'pymcell4'
  testerClass = 'TesterPymcell4'
  args = ['mcell4'] # needed to know which reference data to use

    
    