[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterMdl'
  args = ['mcell4']

[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterMdl'
  args = ['mcell4']
  
[[set]]
  category = 'examples'
  testSet = 'pymcell3_4'
  testerClass = 'TesterPymcell'
  args = ['mcell4'] # needed to know which reference data to use
  
[[set]]
  category = 'tests'
  testSet = 'nutmeg4_positive'
  testerClass = 'TesterNutmeg'
  args = ['mcell4']
  