[[set]]
  category = 'tests'
  testSet = 'nutmeg4_positive'
  testerClass = 'TesterNutmeg'
  args = ['mcell4']

[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'nutmeg4_negative'
  testerClass = 'TesterNutmegPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'nutmeg4_mdl'
  testerClass = 'TesterNutmeg'
  args = ['mcell4']
  