[[include]]
  file = 'mcell4_mdl.toml'
    
[[include]]
  file = 'mcell4_nutmeg.toml'

[[include]]
  file = 'data_model_mcell4.toml'
  
[[include]]
  file = 'data_model_convert4.toml'
  
[[include]]
  file = 'mdl_data_model_pymcell4.toml'

[[include]]
  file = 'mdl_data_model_pymcell4_chkpt.toml'

[[include]]
  file = 'data_model_pymcell4.toml'

[[include]]
  file = 'data_model_pymcell4_chkpt.toml'
  
[[include]]
  file = 'pymcell4_api.toml'
    
[[include]]
  file = 'bngl_to_pymcell4.toml'

[[include]]
  file = 'bngl_to_pymcell4_export.toml'

[[include]]  
  file = 'bngl_to_data_model_to_pymcell4.toml'

[[include]]  
  file = 'bngl_to_data_model_to_pymcell4_chkpt.toml'
  
#[[include]] # requires full bionetgen
#  file = 'bngl_export.toml' 
  
[[include]]
  file = 'external.toml'
    