[[include]]
  file = 'mcell3_mdl.toml'

[[include]]
  file = 'mcell3_only_mdl.toml'
  
[[include]]
  file = 'mcell3_nutmeg.toml'

# NOTE: reference data for MCell3 are missing
# but most of the tests are in examples as well
#[[include]]
#  file = 'data_model_mcell3.toml'
  
[[set]]
  category = 'examples'
  testSet = 'datamodel'
  testerClass = 'TesterDataModel'

[[set]]
  category = 'tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModel'
    
