[[set]]
  category = 'tests'
  testSet = 'nutmeg_positive'
  testerClass = 'TesterNutmeg'

[[set]]
  category = 'tests'
  testSet = 'nutmeg_negative'
  testerClass = 'TesterNutmeg'

[[set]]
  category = 'tests'
  testSet = 'nutmeg_mcellr'
  testerClass = 'TesterNutmeg'
