[[set]]
  category = '../mcell_tests_private/benchmarks'
  testSet = 'mdl'
  testerClass = 'BenchmarkMdlDataModelPymcell4'
  args = ['mcell4']

[[set]]
  category = '../mcell_tests_private/benchmarks'
  testSet = 'bngl'
  testerClass = 'BenchmarkBngl'
  args = ['mcell4']
  