[[include]]
  file = 'mcell3_mdl.toml'

[[include]]
  file = 'mcell3_dyn_geom.toml'
  
[[include]]
  file = 'mcell3_nutmeg.toml'

# TODO: reference data for MCell3 are missing
#[[include]]
#  file = 'data_model_mcell3.toml'
  
[[set]]
  category = 'examples'
  testSet = 'datamodel'
  testerClass = 'TesterDataModel'

[[set]]
  category = 'tests'
  testSet = 'data_model_bngl'
  testerClass = 'TesterDataModel'
    
