[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4WBngl'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4WBngl'
  args = ['mcell4']
  