# MDL to data model and then to pymcell4
[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  testDirSuffix = '_w_bngl'
  args = ['mcell4', 'convert_w_bngl']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  testDirSuffix = '_w_bngl'
  args = ['mcell4', 'convert_w_bngl']
    