[[set]]
  category = 'examples'
  testSet = 'pymcell3_4'
  testerClass = 'TesterPymcell'
  args = ['mcell4'] # needed to know which reference data to use
  
[[set]]
  category = '../mcell_tests_private/models/hebrew_univ_jerusalem'
  testSet = 'pymcell3_4'
  testerClass = 'TesterPymcell'
  args = ['mcell4'] # needed to know which reference data to use
  
  