[[set]]
  category = 'tests'
  testSet = 'pymcell4'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'pymcell4_positive'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']  