[[set]]
  category = 'tests'
  testSet = 'pymcell4'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'pymcell4_positive'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
    
[[set]]
  category = 'tests'
  testSet = 'nutmeg4_pymcell4'
  testerClass = 'TesterNutmegPymcell4'
        
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'pymcell4'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
        
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'pymcell4_positive'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
            
[[set]]
  category = '../mcell_tests_private/models/hebrew_univ_jerusalem'
  testSet = 'pymcell4'
  testerClass = 'TesterPymcell4'
  args = ['mcell4'] # needed to know which reference data to use
        