[[set]]
  category = 'tests'
  testSet = 'pymcell4'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
  
[[set]]
  category = 'tests'
  testSet = 'pymcell4_positive'
  testerClass = 'TesterPymcell4'
  args = ['mcell4']
    
[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterDataModelConverter'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterDataModelConverter'
  args = ['mcell4']
      
[[set]]
  category = 'tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl'
  testerClass = 'TesterMdlDataModelPymcell4'
  args = ['mcell4']
  