[[set]]
  category = 'tests'
  testSet = 'bng_validation'
  testerClass = 'ValidatorBngVsPymcell4'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'bng_validation'
  testerClass = 'ValidatorBngVsPymcell4'
  args = ['mcell4']
  