[[set]]
  category = 'tests'
  testSet = 'mdl_validation'
  testerClass = 'ValidatorMcell3VsMcell4Mdl'
  args = ['mcell4']
  
[[set]]
  category = '../mcell_tests_private/tests'
  testSet = 'mdl_validation'
  testerClass = 'ValidatorMcell3VsMcell4Mdl'
  args = ['mcell4']
  